### ISSUE TITLE
Could I use this engine in unmanaged c++ project rather than c#?

### ISSUE THREAD

**Issue by engine5d** [InKnowWorks/IKW-GraphEngine#2]
hi,
Could I use IKW-GraphEngine in unmanged c++ project? I am trying to integrated this engine to unreal for storing graph data.

**Comment by TaviTruman** [comment]
@engine5d Yes, you can (**_sorta_**) as the core runtime is written in C++, and a good bit of the C# API communications surface is just a wrapper atop the low-level APIs. However, Graph Engine currently generates native C#/Python/Scala DSL API surface from the TSL, and thus your simplest path forward is to compose your server-side Graph Engine App code in C# and expose RESTful APIs for which you can call from C++. The Generated C# code is cross-platform ready and runs very well on Linux/Windows servers.  GE will return JSON payloads. I am fielding more requests for a native C++ code generation capability - I just need to generate more revenue to secure a good C++ engineer to make it happen; we are working on it. I know that is not a definite yes but that's where we are today.

**Comment by engine5d** [comment]
@TaviTruman Thanks, Maybe I will use c++ clr as bridge for unmanged c++ and c# temprarity.

**Comment by TaviTruman** [comment]
@engine5d That will work!
